pipeline {
    agent {
        docker { image 'openjdk:17' }
    }
    stages {
        stage('Build') {
            steps {
                sh 'ls -l'  // debug
                sh 'javac HelloWorld.java'
            }
        }
        stage('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }
    }
}
