pipeline {
  agent {
    docker { image 'openjdk:17'}
  }
  stages {
        stage('Build') {
            steps {
                sh 'javac helloworld.java'
            }
        }
        stage('Run') {
            steps {
                sh 'java helloworld'
            }
        }
  }
}
